import { Link } from 'react-router-dom'

const FEATURES = [
  {
    title: 'Step-by-Step Execution',
    body: 'Walk a procedure one statement at a time -- DECLARE, SET, IF/ELSE, WHILE, cursors -- with the current line highlighted in the editor as you go.',
  },
  {
    title: 'Live Variable Watch',
    body: 'Every step snapshots the full variable scope, with changed values called out so cause and effect stay easy to follow across a long trace.',
  },
  {
    title: 'Control-Flow Visualization',
    body: 'A Mermaid flowchart built straight from the parsed AST -- not a canned diagram -- lights up the path actually taken as you step through.',
  },
  {
    title: 'AI Explanations',
    body: 'A plain-English sentence per step, generated by Gemini when available and a deterministic template otherwise -- always labeled which one ran.',
  },
  {
    title: 'Ask AI',
    body: 'Type a free-form question about the current step -- "why did it take this branch" -- and get an answer grounded in the real code and values.',
  },
]

function HomePage() {
  return (
    <section className="home-page">
      <div className="home-hero">
        <h1>Stored Procedure &amp; Functions Debugger</h1>
        <p className="home-pitch">
          Step through a small procedural-SQL subset one statement at a time -- variables, branches, loops,
          cursors, and exception handlers -- and watch exactly what happened and why.
        </p>
        <Link to="/sql-console" className="home-cta">
          Launch Debugger
        </Link>
      </div>

      <div className="home-cards">
        {FEATURES.map((feature) => (
          <article key={feature.title} className="home-card">
            <span className="panel-tab">FEATURE</span>
            <h2>{feature.title}</h2>
            <p>{feature.body}</p>
          </article>
        ))}
      </div>
    </section>
  )
}

export default HomePage
